spring:
  application:
    name: 'user-service-api'
  data:
    mongodb:
      uri: 'mongodb+srv://ace:ace@clusterhelpdesk.xemb2gp.mongodb.net/helpdeskdb?retryWrites=true&w=majority&appName=ClusterHelpDesk'
      auto-index-creation: true
springdoc:
  openapi:
        title: 'User Service API'
        description: 'Component responsible for user management created on Spring Boot'
        version: '1.0.0'
server:
  port: ${SERVER_PORT:8080}
